### ISSUE TITLE
RX Interrupt

### ISSUE THREAD

**Issue by banksdev** [YuhanLiin/msp430fr2x5x-hal#11]
Hi @YuhanLiin 

I am taking you up on your offer for some assistance with the HAL package as discussed in the other [repository issue](https://github.com/rust-embedded/msp430-quickstart/issues/4).

The end-goal is to do communication via LoRa. However, there is a little way before we can get to that. To start, I need to figure out how to interrupt on the RX pin when I receive simple serial communication.

I have your `gpio_interrupts` example up and running as a reference. I want to make sure that I understand the code correct, so please correct me if I am misunderstanding something:
```
wdt.set_aclk(&aclk)
        .enable_interrupts()
        .start(WdtClkPeriods::_32K);
```
The above sets the Watch Dog Timer (WDT) interrupt which is fires triggeres the `fn WDT()` function every 2 second to toggle the red light.

When the button is pressed, the interrupt function `fn PORT2()` is run toggling the red light.
When it is done, the `block!` is the loop clears which will toggle the green light and go back the `block!` awaiting a new button click.

I am guessing I need define an interrupt method similar to that of `fn PORT2()`, but for the RX pin? Do you know how I should approach, or where I might find some more information on how to develop a solution? I believe I need to use [this](https://docs.rs/msp430fr2x5x-hal/0.2.3/msp430fr2x5x_hal/serial/struct.Rx.html) but I am not entirely sure on how 😅

**Comment by banksdev** [comment]
I just realized that the `echo` example pretty much explains how this should be done! :D

**Comment by banksdev** [comment]
I thought I knew what I was doing, but I wasn't... 😅

I want to trigger an interrupt on incoming serial communication.

I tried modifying the `echo` example to enable interrupts on RX as so:

```
fn main() {
   ...
   tx.bwrite_all(b"HELLO\n").ok();
   
    rx.enable_rx_interrupts();
    
    loop {
    ...
}

#[interrupt]
fn EUSCI_A0() {
    panic!()
}
```

Sadly, it does not seem to work. Can you guide me in the right direction?

**Comment by YuhanLiin** [comment]
Did you enable interrupts globally on the MSP430 (via something like `enable_safe`)? Also, your peripheral name needs to match your ISR name, so if you're using the `E_USCI_A1` peripheral for UART like in the echo example, then your interrupt handler also needs to use that same name. [Here](https://github.com/YuhanLiin/morse-msp430/blob/master/src/main.rs) is an example of using using UART with interrupts.

**Comment by banksdev** [comment]
We got it to work, thank you so much! :D
